<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat.proto

namespace Proto\GPBMetadata;

class Stat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a0a737461742e70726f746f22330a0b5374617452657175657374120a0a02696418012001280d120b0a0370696418022001280d120b0a03726177180320012808223c0a0c53746174526573706f6e7365120b0a0370696418012001280d120e0a06737461747573180220012808120f0a076d65737361676518032001280932310a0b537461745365727669636512220a03416464120c2e53746174526571756573741a0d2e53746174526573706f6e736542285a072e3b70726f746fca020550726f746fd00201e2021150726f746f5c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

