<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat.proto

namespace Proto;

/**
 * Protobuf type <code>StatService</code>
 */
interface StatServiceInterface
{
    /**
     * Method <code>add</code>
     *
     * @param \Proto\StatRequest $request
     * @return \Proto\StatResponse
     */
    public function add(\Proto\StatRequest $request);

}

