<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>StatResponse</code>
 */
class StatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 pid = 1;</code>
     */
    protected $pid = 0;
    /**
     * Generated from protobuf field <code>bool status = 2;</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pid
     *     @type bool $status
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \Proto\GPBMetadata\Stat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 pid = 1;</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>uint32 pid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkUint32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 2;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

